---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: palworld-data-encrypted
  namespace: palworld
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-encrypted
  resources:
    requests:
      storage: 20Gi
