apiVersion: ENC[AES256_GCM,data:kl4=,iv:uFXcgpGYKS0RA4WGZRfXahkEbi4tLL65tLRlM47Fb+Y=,tag:makgDw5XIh5H2UCP9c+Icg==,type:str]
kind: ENC[AES256_GCM,data:RMsMlksQ,iv:6m3hRa043Sag5l8HeDdYaKXPVHQzmfyURAmzhLm8PJI=,tag:JU6mFOJAzwpMhpOv9ibEkw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:YDLoIHFc49YvwCwZsbzwdw==,iv:uH8kkQ0CCBJIfLnWeCHKtL6mEmkC7Hz0T/m3sPFs3cw=,tag:d7A3V9+dRmFi1KmHKxIVAw==,type:str]
    namespace: ENC[AES256_GCM,data:pLVfQ3wkN4k=,iv:FcBTl2aqtEcIjzNumfKfY7oqu5Dc8/IJAD6ekPwsI84=,tag:MUrLyDyU+igqwOn1A3p5Ng==,type:str]
type: ENC[AES256_GCM,data:uCPz9NBM,iv:MIjrZ9flSqdsVj6UUW8RwO/VIPmyBeRKCm63S58fMmA=,tag:D3o+6AMsQ39asm8ff9rfmw==,type:str]
stringData:
    rcon-password: ENC[AES256_GCM,data:blwBYfXGH4Vzgsf2mstUHN0lGRTpXCEC,iv:FSoWNlpH26FAiNqSCBiwjm+HiDUwTVW3bLeGX8G93q8=,tag:4Emjmeh7HGPi0aVC83CgiA==,type:str]
    server-password: ENC[AES256_GCM,data:XWZ1fB0C1Z9L95Bc,iv:DAj7Tz00BhY5POiyIxSoXa5lMCPrnddOEpiEpMxJc+Q=,tag:FVHFAGbnZwyMlxOtr4idVA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNdU5lOEdXVHdOVnV4OElm
            VnhPZGJlaXBqL0R1Z1BQWTNOM0paczIyUmtnCjJ3anM4amR2d3ZGaFQ4TXpYNFJw
            UVVvZG1FYXA2UWRoSVM4OTZKR3NkRzAKLS0tIGJFU3F5QStCa1FuVDczNEprcEdx
            bGNYY3hETkFTK3FnL3htSkE5dUNidVEKC8yAtvq21Q0pdRtDfBgAMaNAE5Zue0lX
            NynQTxrnCODM1jU47PrMXivMegPUxJLTOS8w3ByrsoJ4t+Q5r4vvsg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jxtdxm70ltr637yy5c00586r9q5mfx8ldgw8r5ye2cehpncygupsmjxjwh
    lastmodified: "2026-09-14T22:42:49Z"
    mac: ENC[AES256_GCM,data:BMvwubgQ8DfGGOdS6+VR6c3R8JTHx2H3EbSHm0KtgGczxgZ1vqTYZFr+xcrtsXiborr3nXGM9xZS5DWTaT4DiAys1ShwguxjjuYb6au+wowBhFeXxeKvktV+JInByCxPGRHkQV/5zWlwKKtcog1BkVg57yFKWx09ISgLP4XknnA=,iv:30pmIJqovG+mawxxL2WLadBDnFs+15YrUfjfQzh+kqA=,tag:DN2FxjNUHQQThOwfdeTU6w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
