---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - secret.sops.yaml
  - secret-vars.sops.yaml
  - helmrelease.yaml
  - config.flux.yaml
  - networkpolicy.yaml
