apiVersion: ENC[AES256_GCM,data:cY0=,iv:Nftaxfeg/X+av2PvIwvqhSEFoJ4kzc4BXhuhAsFFL7M=,tag:1egoQUiHvmewd9ZY3fvgog==,type:str]
kind: ENC[AES256_GCM,data:xvQaBS+L,iv:PnkVgWeF9ylnz1w/L3ZFLWW3BFjl5FfbcirvC1eq83Y=,tag:Qz8Ej7nxJjb3W7yIIGyRoQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:hvUwHxy6RWbU/lwXs2GteO8=,iv:2v473uX7dK/6AAhk/xNcWYgq2hxbYe0DtyedF+w4Jiw=,tag:IFCD5prDzzxwMdljHDr+SA==,type:str]
    namespace: ENC[AES256_GCM,data:/QtuSTykK8f1VXA=,iv:NWoyBL/FE5Fie4JsECw4fQlUQixpT25ZjwA+5hu8GOM=,tag:+0MOtn/GMLaAVS9t3u7PxA==,type:str]
type: ENC[AES256_GCM,data:hDC9UGQY,iv:RF39OayB321thMRqeHddx023L+MoPeVme+YZOrGiagQ=,tag:xerTR/HdZDG1TjlZzmVkhA==,type:str]
stringData:
    SUB_DOMAIN: ENC[AES256_GCM,data:Qkx69D0jtHiiKA==,iv:LDlf4/inHd0V7N3+xvawC3ZHm4nKflFbemoIogyabKA=,tag:TCexogH5r/prIAJwqLanMw==,type:str]
    VIA_DOMAIN: ENC[AES256_GCM,data:jlpW8LW7Eq9j+w==,iv:iPe+c+SH96xAU1M1ELrJEGYLuSXVIkXI+BAVKMezm+M=,tag:lqVMlhMrZnSR9vMxYUb3pg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBma0JoRFdINWc1akFIcXBC
            aTNwNldKZWVaQ3hpbFA1ZnlxQ200SHJmQndNCmNPVHlML21wQk1uWXdWd3pNV3dt
            NktMUnZ5ZXBXME1HSjkveCtkTC9EUHcKLS0tIFVwaEtjcnBkdjdDU3ZBVkhabTBB
            bXZ4SUJRMElNNk5SRUNkNXNmTlhmT1UKe24nqlnTZv19XJLn4/TQ1F/5Ij7WOfcN
            xCL/cNIe+JsRqGzqTpKtNW14/U+MuXe3r1G7QyB42988jZ2CHgD60w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jxtdxm70ltr637yy5c00586r9q5mfx8ldgw8r5ye2cehpncygupsmjxjwh
    lastmodified: "2026-07-13T05:31:16Z"
    mac: ENC[AES256_GCM,data:SOD5MwFTE6op8MDLRi0jo01p17c0F1qjdJc0Rw+oXl2sd83Qy+zQo2bAIo2gtmdmb13sKqS+HkqoxW8qCwd4Rfsl+R56MHqqU1DvTNj3SNDpcJUohJGsW//oTkothm2J8Rz+1X2ewt6It/Xpq+s+sqjO1svozCM0tLTI7ODIl3k=,iv:oOPIYAzZZdoK5Xg/mUg4nwhOkpIXozi2ALtnRdDvaPk=,tag:4dKBLNC15vwZcyZv3+ppvw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
