apiVersion: ENC[AES256_GCM,data:gKk=,iv:R2Hq73nGbISZVpTffRI/i/pEWbC/3NhmfU/EgmdYSYQ=,tag:9tObUpqN0C3iSCLyy0+DHA==,type:str]
kind: ENC[AES256_GCM,data:5brPUiKt,iv:iXwjbEC77uLwnnY4TC1+R5KbyVRDEy9fBK1kXMOEdkQ=,tag:68AVXcqf3sV7x15an9CgcQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:mOcI89d8oQNi2XbB0FV4dCs=,iv:9Oje6YMKgjfb9/c4Wp04OqIMOZJgsgnzToXg7cDZt0g=,tag:SDEuQHaZpKO7Kdg8TvraTw==,type:str]
    namespace: ENC[AES256_GCM,data:XaCihkwAA9J6mqg=,iv:0SZ0kX349pafkt94q7J+P5cQ0rqxSpSirPlbfsopyzU=,tag:CEgQ3nJxj/nRzYNgNJnuzw==,type:str]
type: ENC[AES256_GCM,data:UjPGAuuv,iv:U/MrRjiBXH+49uLNLBrn3aeGrgInY5WV3DquVAKLYkI=,tag:XgtzAvjrhxJH9bGJJcWxEg==,type:str]
stringData:
    SUB_DOMAIN: ENC[AES256_GCM,data:N8FdWrd81J5EOA==,iv:xnOzh0AiO19CSlEga6r23FJEnT4postuGwMSBwttCEk=,tag:JijYdoNYDurvkPR+3QTNOg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4V01ZTHVqWTB0SVFHYVdx
            dDQ4U1RlNmhLWmlOYUdteXovVitxL05qT0FjCllNM2U0d2tVU2FhVEsxS2Q1dWtk
            THN5ZUU3TUZHSVJlSml0cENxdGFBMW8KLS0tIFIvTjk5WUVpb2hpZGhWWmYxcTQz
            aDlnaXZnMm12T1ZObUNUQXU4YTVtUjgKdxOcpGdrOk4QMYLtvGFI2P2ePzcBexF0
            E4U8RU3tXa7eAI8da1zpuHrPQS5Uld3JdAITCfEn7mCVCeWOeGavxQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jxtdxm70ltr637yy5c00586r9q5mfx8ldgw8r5ye2cehpncygupsmjxjwh
    lastmodified: "2026-07-13T04:50:11Z"
    mac: ENC[AES256_GCM,data:rKjAxZDbYzP8XG07sbULkbAefAKXLk2I2KD+t79zRZvaabR4pdzBTlTQYs2cflu4eUxEBQQ9c/tJiK7OeWdYQETQEkdGnEj7BtHlMDxZyGrk11IEfoLIKadUIrqgh8E3jGaQPiUqQhyKfYr4bv3rXqUu+4u9yoO1KUnVWCxW1fQ=,iv:vKcYuGJeqlHv9YY8iADFBuMbCcum+Qd1UPVYvVztQdo=,tag:ScViDPP1/9MgpIyF8fj0mg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
