apiVersion: ENC[AES256_GCM,data:fys=,iv:zGf+S7w58egXp51IqO4Np69Mv4X1x+zbjyKOCS7bzkU=,tag:WPkwa4MkuYQPU5LrnYgeKQ==,type:str]
data:
    api-token: ENC[AES256_GCM,data:NXZNb/7FbkMkbasdVM+LulOM1wKEoSHimh6LseyFZ/4CTizt7r0YRvjc39+S6EzqX9vxWzSTgxLZ6NOUOnY/DccWiAelT8qp,iv:vJJbZkRep53FpVer7N3M7gAUGhw4lILB69C3+ScSHi0=,tag:YVpxfl2f0UFtzkQoWrs46A==,type:str]
kind: ENC[AES256_GCM,data:S9rL0Xm3,iv:ZmNTPKBkgM1lkQDeoy9CJpxukijnkKYE0HUsKbB39WY=,tag:fd8vyahGfliSffDVOBxacg==,type:str]
metadata:
    creationTimestamp: null
    name: ENC[AES256_GCM,data:nDsEcx7Of7kKc4lr/VHdQQRej80=,iv:hmxTR6b0t0ogj7ibP2od86p0h/SRbfHwY8SUuSzXA+k=,tag:Df/2y7Kru5XvxkJzndtu+A==,type:str]
    namespace: ENC[AES256_GCM,data:m8X0jHX2nJwcXUGm,iv:0cppvBqNBVH/XRPmR3+JVWoMRYMEeJitZ6aDoUY76jM=,tag:OAQxmPaGDgVir7IL+eRSQQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiOW4rd2V3cE1tbjRLampn
            U0wzTXB2d3YyR3NpekhwTUQwcDZqdTdaT1gwCjZiRWxtV0VEazVRSGs0ZDlGc1VX
            Um4rOXN0cFVaM1czQWFsamdrVjBMeG8KLS0tIHRsMDVRU0lOWWZiMkdXMGQzR3J0
            ejBSSlNZOEJOaXNWT0t1a0pQWERJVVEK4eQl8FIl/+KiTPv8/NiFlffjQU5iNelf
            nWN2ySY9CZcex43CYufm3TWp0xS9MWKc9tJNJKmUMDoovapwkhxOig==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jxtdxm70ltr637yy5c00586r9q5mfx8ldgw8r5ye2cehpncygupsmjxjwh
    lastmodified: "2026-07-13T03:28:53Z"
    mac: ENC[AES256_GCM,data:YZd0h6dbK8qvpn9BvJOrgY+aOLJ0V0C0ftxR34lEsMUiI/D/DWPQhVY+vvNaIQDj1HCVSh7J/0Kxf+fDY754ffiEMotWiNqUvhLresk5HUgAG9J6FPTEWEJ+ZJyP7YVm8P0Ar65X5zJ23J0UZ/TGVah8nyLt7DCfJY/R5/z+f30=,iv:sfPcEq2ZVTd4EyuyeY92zI1v3yuT3sLK0E9+Gm1p8fQ=,tag:7JUZ4hiWqzfJ2Vd9mYONFw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
