apiVersion: ENC[AES256_GCM,data:cjY=,iv:gYmNEWbX5Wq0I57vPFL+ItPB0s5IErOXkNVV5nxhoS4=,tag:MSUFS4/mgKwFw2YbYD4IDg==,type:str]
kind: ENC[AES256_GCM,data:JwKSrEy9,iv:CLrlHtXabmFvUntSJIfwCsGKM5SZIYIy792CK3kPRxE=,tag:AgJk21TIdna1ZKC2LQcaKw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:4eWUpwOqtISEqlpUsfeM8A==,iv:W8g4YgrtXJjCBAIvsgPI44oMF3e1oKd+JexQ8mKT2EU=,tag:7ihDhxEPXoS8mdITAleLdA==,type:str]
    namespace: ENC[AES256_GCM,data:SXVvxsI08GPk3XA=,iv:3JsToC40Pk8h8Ob1zUQVluCtQ/ZZWe1ESLF57dQn1HM=,tag:PK7omI67qlIzx4ucXuWxNw==,type:str]
stringData:
    FORGE_OWNER: ENC[AES256_GCM,data:KiY5lrzM9kChiA==,iv:Wpm8GH05av4+JJ1uQNA4I7vsJmMAEwyrjo06Jkhj6jw=,tag:cbrXnim4BRNUSCh8fKt9Mg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4VXFnRkRzWmRtUUUzUDZJ
            TVhyNjBsd2xpMEtXZ2N3QlZnd2FuRUFnb1JzCkpMUElkdGNPczZ0SDc1d2w0WGlD
            cCttSFg1TVR4TFBCZ0Y0MmRzdTdBWmMKLS0tIFBnUjd1S3VWbHVWdzg0a0dvdXVW
            eXZXQkhVY1ZPc2JXSm9MNXNyOGJKVVEK+3RrJ65cO6EQi71Pgy5pYVjcVrbDt0hx
            WQRtfnGLwFcFgfsn2W/D7gG/lOfJ+VRI1N3Y+/enBlQ2TPrWaCO0wQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jxtdxm70ltr637yy5c00586r9q5mfx8ldgw8r5ye2cehpncygupsmjxjwh
    lastmodified: "2026-09-30T03:00:52Z"
    mac: ENC[AES256_GCM,data:fHlgxM+86wHsmDisAf6nsUDCF8B2KHgo6uIDa4E/rYWcZDjYnXk5pxSBMnQarhoId4n1ZQo/Dx1E/qb07JlXmaovc2z6BIo+GvMHSpHVnsevjHmSXFWJrDlrGGjyIeg08xfrW0NDL4Mio0Te6ZBXoQZefz1NPczDXmAHAK6C/5Q=,iv:hT5Rz/L/toDD1M3jnlTFD79QkoatmOJ+lw/1Jyb296M=,tag:PJanIoF6wl42DF1j3XMTMg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
