apiVersion: ENC[AES256_GCM,data:JEM=,iv:attxAZPQjaG74uwMs6xUzdsiMRX45KZi5Ie4GskTeJw=,tag:XF1Z0XoZ1KAjBUT32MjuIw==,type:str]
data:
    token: ENC[AES256_GCM,data:AXuzvkM6ogD0CSkR12bCfbocVp6GvUswT6KmGh44lKygL0YX84QexIyif2/xnKswyOHtEBk31II=,iv:06LORqA2tfrUfOJrPUqXrpKl2RKnULyt7UAhDqwrzMI=,tag:P6UJm33Y19FYPVAn3mPc0Q==,type:str]
kind: ENC[AES256_GCM,data:t1+isTm2,iv:Y+1hFtg8cdctgIxkhq7tDSgkJDHwhByJgPlaZR5hAtI=,tag:s1bund06zed2ZhUW2TJp5w==,type:str]
metadata:
    creationTimestamp: null
    name: ENC[AES256_GCM,data:U/kEePfdHNz0q2VpWgwF7DRHqQE=,iv:uB5TTGFlTSFePxyHg9PStk8Sp25Ay3Ib13poGdgqD7c=,tag:ZuuX3a3pBJ++On86NTN8nw==,type:str]
    namespace: ENC[AES256_GCM,data:1PNW/BabpvT/XaxRu0c=,iv:Zqce0yvrlG8H1x1X3AOantItyXCb5o2ZSDJDGHh0vto=,tag:FZBHBuB5zVXLP/O2Noo0fw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvcVJma1JGSDI3ZnVZUm13
            VnRVRkFWM2JrWFU0ZW4yRFZMM1QxTU1JemhjCmM2K2lCL3pES0NaaWs5NW5YeGE3
            NllpeUxPQ3NZNk9Ednk4N0tTTEx1NmsKLS0tIGxqNjJuTjNKRHhoV1pmQVlvbGlY
            SzBvdVE4aTQycDVnejNxVWphWkR3SkUK0WbnOoUXqEnzASYQs/ODadWtIVAhNe+4
            E4x+pFMjYOgRdblppgfeljSFV7ADWkq3uTAHh+JaH33KXMpNGzijSA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jxtdxm70ltr637yy5c00586r9q5mfx8ldgw8r5ye2cehpncygupsmjxjwh
    lastmodified: "2026-09-22T04:20:44Z"
    mac: ENC[AES256_GCM,data:shuy2dS1IDPLr4JEKnFLIO0hZlWfaHj5WWuedTB5+u0njELz+BmBgCaLJ1SzBnwtpGPXiks65oOUVLTONmW9kkNEF78C8Doyl80DfNp6jMjENcsD9DT1WBP0xGUeyVeISTmkJJpe01NU4e12uD4nq7haZ//gZjRfBz5T5tnXTGI=,iv:NwqYB/zv1SX2X1TenaM+v1axRiscUD7Fi72WaU+yVac=,tag:jiNRtE9hAfIoAypKEwMNpg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
