apiVersion: ENC[AES256_GCM,data:vqU=,iv:2OC2uCftPNuwDVTcKKZaHsXB/WVV5ef7rx+WxU1Wn34=,tag:p55XZOERJyoy2zkcSfZvQw==,type:str]
kind: ENC[AES256_GCM,data:OfBqcCqN,iv:tfIAhU14eo/lk3EKn1jmo4+yMofCmW8QR9c0QjdVJ2I=,tag:WWRayaP4WanDzZ32Vx0ulw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:51eywpNQ7GbCAX4G3D+4RPphaxV3,iv:zYD0IgB1mHQQSFf04S/1cpWyIWYOLmH4vOe7FD9/vPo=,tag:u4G58vfjE2/RBci4tMaLYA==,type:str]
    namespace: ENC[AES256_GCM,data:h2RBBmWNS6xXdmKhBtA=,iv:9VArpBvdh0+6JNBQdzs3IxGFTCEx6zapa5wqecxkzLw=,tag:Gft23/f/ZTp0Q0Sie+oirA==,type:str]
type: ENC[AES256_GCM,data:5uTrOF6R,iv:bJLkz2bNcZPkQ2rU7FZXUfXQPuIt/9bo2Txi+alcUvc=,tag:GwQeV4vHmXg3oedmD8sMfA==,type:str]
stringData:
    secret: ENC[AES256_GCM,data:olDzV34/3ktLfREkUY7jRTsXGzRhKGPkvEBrPWte5N1Ed83mj4hoDQ==,iv:+uKOOkwmVBO2sfHlRVm9UOZQYHd8+fsZA+IStAEv8j8=,tag:FFP58WBjfDzqxcGSLDlcSw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6ZXBkdFhmc1JVeTJuUnBl
            VFNWMlo4ejZIWkpybGV1aW1NcTBLVEF1dXlBClNSTE94c2Y5b1NNNkF5RDhNUUJZ
            a245RVQwN2tBODlSSjNxUHcwbVR6QWcKLS0tIDU0d1JiVkJNcDYveDhROWtJcWF0
            b0Y4T2ZNZGdKMXRqWHdCNkN6NUxjamsK5N8Grw+UwZPV0AaURY65fxlNvNlCC1QY
            ZWoct+U2KLIwYJPQHZJ3Xpl3NbKDRf81L//8j7tAXnW6QrQsAiP5Jw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jxtdxm70ltr637yy5c00586r9q5mfx8ldgw8r5ye2cehpncygupsmjxjwh
    lastmodified: "2026-07-03T20:05:40Z"
    mac: ENC[AES256_GCM,data:33j5DhZ1abmp2lV1uug0ER8p6RAmKsWwnkYUQAZqlTvAXn2+RnQxU9bC01RCjQc999wYIx3KLJTTHwwJrYunfnx4oqUyhMXbnVH5SilzG9DsI3HZF4R4CCR4Ix8VRoa6YtZPpjWy01gpNIzl8BFALiLsweIkYSOcOBYUZ0p5mAY=,iv:uxgdIHbLYJJ/UDzlAbErg/dCMedXVXD5yVvPLO99tS0=,tag:FDj7I0cm+JNC3NcTOP7v3A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
