apiVersion: ENC[AES256_GCM,data:Mls=,iv:5EAFRd3+ZmIQ43y5ORucKXW3dpyzkC8l6WHQ7/El6dI=,tag:KgazcxrAt1KLwWC+KIIZbA==,type:str]
data:
    token: ENC[AES256_GCM,data:m80d1+O/nmLYxJ8trwTqX+EaKw8XPf9q7zJdyDC77YslY72Isjx1ee1liNQp/+GtUMBfgUTyZ+Tyr5UR,iv:BdELvQ2nephzVBLjAGvtCm3pzwEgr2/mIn9h+0iMJGk=,tag:qINeNt57aa0/YFAew3D+nQ==,type:str]
kind: ENC[AES256_GCM,data:+RIJGBDd,iv:6/TOouMks9YEv9Zj9axPGdezbpkTRT0Q7+sIwaeRrpk=,tag:VmY3E3LYfdAXcOi8LMUf8g==,type:str]
metadata:
    creationTimestamp: null
    name: ENC[AES256_GCM,data:6Xqh4vai0i0MWeXvOn/WBfuGx+A=,iv:/u1pjd1cy0w5ZR/ybGDKAppLzSZZA6ay9AOyVXOqR3o=,tag:PMixXfrm5lw6z5xBnlXOpg==,type:str]
    namespace: ENC[AES256_GCM,data:WISjF9aouwbkjVt0qyw=,iv:EySBXlS3okJPDXnOP9p0/uFF9W+GyejgTtezUEBBI5M=,tag:NHLqyZVE+jG5rXGYjr2rDQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtdUdKRWpoUU5xTDlGYUls
            bjVxNDQ3OTBlZ2l5SGN4MThNTnZXZGhESFZrCmVVR1FwRDZQWVEvc21yMy9FSkVt
            WW1nYVRra2l6QVJ1elBHMHRtQnhXYUUKLS0tIGFyWWlvTUJ2MEF5Q294WWhJcVNt
            Rk9VODBQNXdNcGM5K1JpQXNac3o5R1kKD94s/clJlmJQH+cBPK81xEo4/6LtWwgv
            /q9py16jfw64tMFXzn2Kw9KTGDzkoOBRv+VufAjpTcMDlpQEWZrrVQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jxtdxm70ltr637yy5c00586r9q5mfx8ldgw8r5ye2cehpncygupsmjxjwh
    lastmodified: "2026-09-22T03:55:58Z"
    mac: ENC[AES256_GCM,data:6IOlTiUaay6vHc3cufrBcrTDI/L3e0bwi1FeZ5cskilRDU4/4/OlORdNNiZi4aaT1D8Io9QWKTcTeW+tVFEq7vTcBQf3TPT9YBJRlJy0nkcvY69ocVSt3/9Mgau+IuvUEv76j+yuwT+mDMawlTMbt2dFA0ygNNDFBHzWTFOBlm4=,iv:/Z7g955ps+JzLR6HLwBwGI1esbKVsjay2267smEp/eM=,tag:quuKE8coe1DDOGv5kyHYzA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
