apiVersion: ENC[AES256_GCM,data:YzU=,iv:Hmfw2nmwF6Vkoodr9dD868fFZMAoihLSBen6Ys1HhQE=,tag:YkbqPRQdrUzJKxeygGRoHg==,type:str]
data:
    rootAccessKeyId: ENC[AES256_GCM,data:u+fMNuKbd70TwDDD,iv:6aBTDHvf4foIvwOPwksCOmUU2nmqzFHCaPNY71jtDYA=,tag:sOPbBDqfX3Nq3CyQyfn89g==,type:str]
    rootSecretAccessKey: ENC[AES256_GCM,data:avXHMNR6D45biKZ7F2VZqggKvBNTNGCa9rb4iKn5sM9BDGJQbxkpzJMNg0ETY9s6iWqIuW8oi18=,iv:vXlaqM4UY88iviqbYRuSC/MFNmtiofUx9TtpfcjbBhM=,tag:WyWHTfKJdfS6lQ52bNLnWQ==,type:str]
kind: ENC[AES256_GCM,data:fDqpvb0T,iv:bLj+isjyPObJPXunBi0NZ8ZBRxZ0kKonxshMhMXOkSM=,tag:P8nBc63P9tgisSUenblW/A==,type:str]
metadata:
    creationTimestamp: null
    name: ENC[AES256_GCM,data:qSjTQvgt3Ipi4UmvOeM=,iv:Wgrz+s4d409ozf/N53VRD+RR+8U6JtcCg42VrlIHlXw=,tag:y+moPDHu60XoDDppoaH1Mg==,type:str]
    namespace: ENC[AES256_GCM,data:NNzY1wDFuM20,iv:B43Wsr0wagTV9Y5eTGsY53f01jHxv5qJtzkf6cxJwG8=,tag:8crQzYZ6d6fV3jJEY+aSdQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5Y0wzZXowUXpjNXJZNjV5
            bmJmY2xtSHNuL1lDTnNMTTBvTnBuaVdxT1NnCnVIcXBINVhUT2lGYU5uMGhUOUE0
            aDNvS1c0bkVvOURZSCtiajdWZXgrVWsKLS0tIDJ0OHV4Qm9XZHAxajN1WDdxL2M2
            am1ha01ZSytFZ0RkTk9XcXlSamw1WWcKSzdApYk1yOLFmNB2wF0XTrlgPVqyqAIA
            PhtrbS2o5rYuc/SR/O8HquhECJGtMPYi+UmbUkvnjdoBeSGpmBhelw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jxtdxm70ltr637yy5c00586r9q5mfx8ldgw8r5ye2cehpncygupsmjxjwh
    lastmodified: "2026-09-24T02:05:16Z"
    mac: ENC[AES256_GCM,data:7zwVohQLARrlMpoO6lJy4c6Ykgwv3/H+iu/ZnXC/3whFod6o8kaKSd2wsBk8fHm65487NiVj6pomELxchJDaeroy6IP6p7Hkpn3U5qHJnKzV/lOWKAw1CXHZ+PJ0xeSK+N9R6SgUCZrnAkTaB0tFWB14V/IP/YqhkeEGA2qjzx0=,iv:pkCLVDKoJDMIsnVlZprAumVPIlDxrGRA3SspNPL1LkE=,tag:2NBjFjcO1YD/IvZPCYbsqA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
