---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forgejo-data-encrypted
  namespace: forgejo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-encrypted
  resources:
    requests:
      storage: 30Gi
