apiVersion: ENC[AES256_GCM,data:lgk=,iv:VNWWKKNT48YDmwSggyACZHPo/eC+t1VUM2YxgUI51q0=,tag:PArYVty/TZdinXTq4bRhJg==,type:str]
data:
    email: ENC[AES256_GCM,data:Jr+rV27OAoWy2stKYilSoUlhNEQ=,iv:WuWxnWbYDwXLtIetYSqGE7uyQi12IXijGlXQhA0B4Ek=,tag:so0dWYJz0ICX8CqnW+Yz7w==,type:str]
    host: ENC[AES256_GCM,data:PznBbuZPK4Errpz09+qxwOgpZ2YLpa0d,iv:/6K628mVwjtJoPl7U2o+oHhIuJUn0+Jvu+VBNJ4QXRA=,tag:WX+PtbnvXkjX6zaOyisoEQ==,type:str]
    password: ENC[AES256_GCM,data:42r/UGeaek9sQKUj24z3Xi2IztWkBRxOAvzkagnfgmk4rxiaEsrWl4TZ1ms=,iv:LYFJmvvp2sJ27H3tB3ikU68K0hx5vnEcyY/k6SYUtDA=,tag:KgPZsWgCpgm3mD2c2wNUNA==,type:str]
    root-url: ENC[AES256_GCM,data:PP8YD6OkXqAw2U9n2eb6OEjASK8YeblRGTdgroNk6U2UZ1/q,iv:jfeRLCSsxQACU/voYg55zMgXHlhLH7DoJZS9OOd5U0o=,tag:hxDY2rkblKjqbfbntO7nGQ==,type:str]
    username: ENC[AES256_GCM,data:hb4AjmxWt/BimSgzVQH2wA==,iv:kP0jcnAifH9BRmYXNCUKTL+moK3XASwDjrT+PcjCtvI=,tag:ejPs6OtWCnaWRhPq7Fkicg==,type:str]
kind: ENC[AES256_GCM,data:kYZKFual,iv:2vjz6isMti2IdGWNHDVO+qTiQSYLwgZf1y/ls2jCfXM=,tag:LKQnUjEcMMcAYtPo3EliYg==,type:str]
metadata:
    creationTimestamp: null
    name: ENC[AES256_GCM,data:3+o2rm14Zyfn8ULSreeW,iv:06Grg3lxP+ZNPdPx+Pttx7m+icVOITUR+e4X7GRt39Y=,tag:MKePN7yy7NPiW9T1of9SqQ==,type:str]
    namespace: ENC[AES256_GCM,data:f275zjtEsA==,iv:mLbZVqySJzwokqEa8XLHed83yO7SIb2U57RSub6nh08=,tag:ZDNKS+4i9AGvbpDVfhKHCQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrUWlNakRPN0FWTFpaNlZR
            bUM1WUprM2czeCtCMi9xNTkvYVhmMk5QYTM0CkhXNHo2ZStlalFRY2VrNENoa3Ev
            WWpySS94MVU1U1ArRnVMVFNXeG5GajAKLS0tIHpFdXpQRFRoMlcxWEluR1Y5ZnRE
            c3V3dWJlVHB0ZmtMNEtZZHEvSDJsdlkKBxPJoR1nBrdn+M085mLp2M10QRsiEFSR
            Y14tnJYn5iub9eQGN9CEe71cdNlpqhJ/Rnrow7r8MC/ffu+c5A/O6A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jxtdxm70ltr637yy5c00586r9q5mfx8ldgw8r5ye2cehpncygupsmjxjwh
    lastmodified: "2026-09-22T03:38:43Z"
    mac: ENC[AES256_GCM,data:i7TqtWqCTsnOFx8Q9U4wk9m3SYuURwgQ4InqXT1QYG/zAk9Ni8OUIw5Tmo6qvMnlQUDAr+kTTpXKmgq+J1fUW/KCoTALowZJdroL5dxgdh/xXHfGpZ37OXSgsS7NUFMqE51+d3xHqHd0nvIe1cBvczzDU4jlJJTjJE8W8ZWHSmE=,iv:fhAehrKUrUGS3UD2IDFcis29NOW3nkTaQ7nz/hhKhgo=,tag:GN72OvSbPCJ1ClEJPMaKiw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
