apiVersion: ENC[AES256_GCM,data:Vsc=,iv:V4Qhowlds/cd7kdZVsmL716AXj5zh0u8cwl7WHfknSU=,tag:NpN3/vgXt5qKYdRd0rEJXA==,type:str]
data:
    email: ENC[AES256_GCM,data:HribLPowTAZqBoMji6vGTf4Qsr3iERIwvO+pcw==,iv:oyrhBVyCSUrA8jwKjD05BnoFmRJ2QEJ0f0WQaSsuX04=,tag:I/eo2URZjhtKI+lKdsVqmg==,type:str]
    host: ENC[AES256_GCM,data:4Nrl3hFD7O0Ox7UU6dK6Ug7MOoo8Gwnc,iv:2RDJ8b3cuAYzWpsQ5ATXDR8pY4UM3skAdc/EwuANJL0=,tag:WocwwuGjQNFb1MsTh7m5HQ==,type:str]
    password: ENC[AES256_GCM,data:U/DStbsbFLbYSih26aIrHkHgEZw/7sCyf57m/TFGO/egbwsrLY3w0n1gVsk=,iv:PY1JcWstmERKTfsB6bKLjo+vqlxvR3Wqs4y7kNoQWRI=,tag:wLAKsT6V17klQNWX3swspw==,type:str]
    root-url: ENC[AES256_GCM,data:f8ON4z7r6F2+UCkayofEE3tRUrYsqI8S3wEqXuB+HR2gmAJ+,iv:B3ehsp4WONxupG/b0WcTOgmji+m/cEejf7TwgLmtF7A=,tag:PnvEPPNIBFEfAgNlNGv1dA==,type:str]
    username: ENC[AES256_GCM,data:xEU8i3Z5uAw=,iv:5Ajny8p8IKxFSXCmr6dDUdGVsznUpHr0F5yYA2QdrtU=,tag:FsbXJKdaieZeUg4461/9SA==,type:str]
kind: ENC[AES256_GCM,data:we1/QG9Z,iv:FIhr9jZEZzKK5HuyKq2V2ApHNX6A/OnxhENzmL6mIjM=,tag:FPuojGYuV5WS9oTrxcUwWw==,type:str]
metadata:
    creationTimestamp: null
    name: ENC[AES256_GCM,data:jUfN9f6G+sfmDkzsOtsO,iv:XybKONtiOz8N+QFpAgYOFPqjiRpQmEn03Y/xyggg1Y8=,tag:WGaGjHcN445CyKVEtKj0Ng==,type:str]
    namespace: ENC[AES256_GCM,data:aHn4Oxzt/w==,iv:AjcHflqudzvTOE/LoTOs2aOxTazYutuClFMwvjbT+5M=,tag:Tao2s1JYJp20EHUZpDxz/w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxaDVsSGhoeDVvMVZHWGRE
            b1B2OHRhc3E1RVJFelFJNGZxN0dFeFIwTVMwCk0yMnNLeVpqY0x4Wk5vZjM4RzZU
            Z0N2MndLRENPZVRudWd5djhqQlpQWjQKLS0tIGorU29wRjRHMlVQbTZ0dHJxOUhW
            a1lzNUNsaCtuZFlnQVR6R0xPNnRCb1EKlSBRMtgK5RnAqvSJyJwP7TGsZa2dmEdR
            vq2wyVDhuLj363WT7pLaEHMwmRjJyF4NRoN79PdO0FDoWfnUerKvog==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jxtdxm70ltr637yy5c00586r9q5mfx8ldgw8r5ye2cehpncygupsmjxjwh
    lastmodified: "2026-09-22T03:25:53Z"
    mac: ENC[AES256_GCM,data:pKBNgafgoZltmiM8gKyylZkwvQrFyBhKmFBmBcjb4sA1l+KEhWD+f4Sm+y7kcforSalzGxee9JGtdr8eAXb0quAi0mdY/RCcSS44rZU0Cibh2MbTL73pZhnJsVWBYf1DS4LlLyb/sWp5CnvS1OgfFew8Mr7uq9+ccy2SpthIf0I=,iv:pf+kTYq4gYxmRFt6twiayo7uVLXxoeosVcOr4cv5RRE=,tag:caEJUnHBeaupzLughB5EZA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
