apiVersion: ENC[AES256_GCM,data:1xY=,iv:OBImMjbfHV2QQW8/lYGoAuwqY5j1i9uazfZYOq+dRrQ=,tag:ZnGtEd3UBJ1DNsRpbrmazA==,type:str]
kind: ENC[AES256_GCM,data:J1D9FzfJ,iv:r+33xMimRJe0VXLwBw0MFN8oDW0h6ksgYpE7yrWVWi4=,tag:jiSusvnW7mbDZmG5u3LGRQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:u6VJsRFlCAJCsdQ/sUJL,iv:kCPs9MXgQrQDJnO3ZN/eB1Qjr5yZkoIlk3FY0pMXpBQ=,tag:2l4L6IRP5amv++o4p0IqrA==,type:str]
    namespace: ENC[AES256_GCM,data:ooz3tq7ndg==,iv:3Ar1aNMadYOQiJtbnVizYrXE12WlV+wSovgsj5LS6+c=,tag:nv4K7JEXPVMqpxdoYPwaTw==,type:str]
type: ENC[AES256_GCM,data:Fw8iz/hf,iv:B/1xiz/JHgG6fBmfw//YCmDmkckByHP4wlStbFEGR+M=,tag:LVUwgZl4GwehksUJEAUPOA==,type:str]
stringData:
    username: ENC[AES256_GCM,data:zFfYdzI5kB/wrcc=,iv:9qJh8jf98zPefCmtNt0dzU4wfjW74Ml+aR6O9XM02aE=,tag:5B9/0QvbZ+uKpIkbbIRQrA==,type:str]
    password: ENC[AES256_GCM,data:ZVEYVKqKGK0HzFvaeKh1OBUOBJPY7F4+rqTVCJV8l4Q=,iv:aCHAozkHekyd9yaqxya3wXFEZOCU2Yzz0+QhJ4TP3gw=,tag:fFQyq1LgXmT6eMsfhEUcXQ==,type:str]
    email: ENC[AES256_GCM,data:Bh0JBJcduStZ/s5SRjXB/BP3P+zIzxw=,iv:jsiXT62qaQrNforbNh2RsC8iVH8i9CO6H/FJHgRtGYo=,tag:cpysXcsF1luvUBZnjfzilA==,type:str]
    host: ENC[AES256_GCM,data:9qxGRBT++lxj6/u6H7CFTa0SfjRb,iv:oCIqsMzzYTV4mQiggYlG5Bc3aiOKFb9r+voUa4lTN/c=,tag:WkJLM998ApE+deN+uNN16Q==,type:str]
    root-url: ENC[AES256_GCM,data:lcHx4MgqXdVQYvWhPgF0L5OBqiyxVc18gZF+yVBy,iv:5qExG4a1h10svXRPDgbxHR0jaJ6IiMawRueKolW23Xg=,tag:R76bPVkTssB68Xa4C8MEXQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwYXorUkxXeDR1KzZjT1VP
            UHRSRFZpNFU0UWJpdnFURDgzbG5ES1hLaUhFClMrUGx4dERoQ25GaytNRE1lcW02
            UFJXRkxzZ1A0SGxzOWxyYllkd0xWSkEKLS0tIGN2RkV4cUJlMU9Ca1FsSTFzaEJv
            cTdnRUFwbWpIcklXMU8xU2k5TUtjUFEKzq4pdYhW4m3QFweRbTSa3OqJThVVpQKY
            NBRHMA5m4RtaQUeWLTu/dKoVeA4DvwQJOy4XzIQHCLr/V48IUySmdA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jxtdxm70ltr637yy5c00586r9q5mfx8ldgw8r5ye2cehpncygupsmjxjwh
    lastmodified: "2026-07-04T00:10:20Z"
    mac: ENC[AES256_GCM,data:eR32mgMBWXowfHFBt8H71FwFN3bLRXRbbknRLc75dCxy53giE/EztsSvRTac679+W81LWIVgauUnSs2oFYx/eC4pE/ILRPiU6CUfgdZQoTbdgeMPd6czhBlPewbOgrqrXAY3u4bhuIbHAmJ0B4ZTmeet99w7FhNKTq2k8VVwD4c=,iv:y/l129EjvugA9GL0KwaXVajhuJRADiJUd8ROl2Hp2WU=,tag:1h/C8xBjEukxibKUlv4q/w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
