apiVersion: ENC[AES256_GCM,data:q2w=,iv:agD+5TM+SRufoa3t0XXN6lpnI+VpxvYWh6rmjsssUvw=,tag:HBzBpAi2yyvk2dX66MVtdw==,type:str]
data:
    FORGE_HOST: ENC[AES256_GCM,data:BNlOm6F/RzpSVwGgCoJzKZHr26aQRoMm,iv:DNDEQWnhh889pv9XMaBxfbwQxWvW9zof0WCdpkIfwJM=,tag:XzZm8rtAlVVS3XZxc6hO1A==,type:str]
kind: ENC[AES256_GCM,data:1DqY1GZX,iv:b7Mp7jX734RIwOrzv/Qcc/X34ewDx/5nvfCXsPPaU1E=,tag:hVu+ejpGEwLiBx50LeuPxw==,type:str]
metadata:
    creationTimestamp: null
    name: ENC[AES256_GCM,data:5zpSh4fnS96je5JK,iv:FeXN0Kdz1xL34qVAsQLjnvpLmEjLVUxxk8tAxV9shOw=,tag:2s48nbig0PF033ACyv908g==,type:str]
    namespace: ENC[AES256_GCM,data:jhXDsQp2TwyMKFg=,iv:P0q1uwa5Ow1e2IA7Z1OOBA6k7AFkFswZg/lkMuVLHY4=,tag:IrR87fhpuvVFk2LrY/iGQg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzb3M1OE5tTzBFd3NFWVFt
            TDNsNFdnQjl0U3htSUlERGNVMHhlelZPN2k0Clo0enFLYXUveFpjZWVEbVFjM2sy
            WG4wbWhlcG1TTUl6SytSa2xrVDFZQmcKLS0tIFpkREFCdWt5Z0ozKzlQUkdTZGRp
            WkFKeW5zMG9vbHdiRGp1TEcxQlRmZWsKKnGCgEhEsL2cUatm6DAZveouEGxlkE8o
            peTwRRwfzz40rdyXagqmV/NcZJPSAMtFFp+fkUYg0vSkfuhZdLwjDQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jxtdxm70ltr637yy5c00586r9q5mfx8ldgw8r5ye2cehpncygupsmjxjwh
    lastmodified: "2026-09-22T03:25:54Z"
    mac: ENC[AES256_GCM,data:uU3JPaPjKpYBZA2PYa+Jpmcxqk+DfGGWpX/qzblMPR62luhBvOwFpxvr9Yq0R1xJJY/Z50UAbXJS6k6dmVAvb4hiH8EUnlRtfEtW2tS1ybskJoMBPgW4JZdpuvyYvEr4EB1m/qxMEYUgYIDwl7btT6Ur8SaCK2c/0hc/r7DheG8=,iv:au8vxIuB2TFVLxPN86ddcqOMdIV2gg8+4DZUJdM4HB8=,tag:BFRPz58PuLk8SltxECB6KQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
