---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  - secret.sops.yaml
  - secret-vars.sops.yaml
  - secret-basicauth.sops.yaml
  - secret-backup-target.sops.yaml
  - secret-backup-vars.sops.yaml
  - backup.flux.yaml
  - storageclass-encrypted.yaml
  - networkpolicy.yaml
  - ui.flux.yaml
