apiVersion: ENC[AES256_GCM,data:W4k=,iv:v7w0xl7G9OWJIJ2lY61dpYc6am7gMzAZv3qv3KR/6NA=,tag:GFFnkqlL6oGV4HR80trDLw==,type:str]
kind: ENC[AES256_GCM,data:1fzEKv26,iv:tV/eQPMuQVbQC84PwTUhsACoC1PyKYbLXiLcz3mHI6c=,tag:S5NDGj+Uq/fJ8OufiEDcUw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:DACZW9MEIffwAjJsx/SWOUt7zrQ=,iv:NLrMqNEJteJ+SCNFttGqI0nqIi357AqUVIH+4ZYMR54=,tag:NxFigZzGZVuTAD90Hgzs9w==,type:str]
    namespace: ENC[AES256_GCM,data:DpvU0tMXje3RBMw=,iv:gLDADo0FaYcDeM4uHv60zpP1tS1GEqDiWLB4d+VuZeA=,tag:qR/hrIzGxOMJUmjLWO+oqQ==,type:str]
stringData:
    BACKUP_TARGET_URL: ENC[AES256_GCM,data:XZ/B/NxKfEihAhPUAmyXhrRB4+jqxTAwC6nLVDHBljnrnR87,iv:+t5qW++57OxgNX6HC2+YvvSP8ZWtNa9OQ71b4Hh1LLk=,tag:IIpaafKW+/0EhNDyKRTxCw==,type:str]
    BACKUP_TARGET_CIDR: ENC[AES256_GCM,data:vFAo6lRDQ+3mnjgHLHui,iv:Aiqpfz4/5i3KMz8J/ibc+mSgpCCyOBOWaJqrb1jyJ5E=,tag:jZqArYykiiPz0iHnBjJdKQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsVkRpWjNUNmxZYmtCUXd5
            MjBkTHJ0K2xpaVM3MWl1b3RZUm5XVDJTc1I0CjZSQndDNnJJRlhBeFRRSlhtNFYx
            azZ3WFJhcjdoOEhhVlRvODdTQUlhV28KLS0tICtZOWt3TDdXNmRLOEhrY2JVcjBW
            TmRNb0RNUkxTWGNrTDZvbTQ1MHJIWmcKFN0IatEwsTx6xYU92DecUfKycH5UOvvy
            xvgU+c1PI0PMCxiy/7FLmh6J539q0AaO1Ng5PMeL+ByiUMJz9sjOeg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jxtdxm70ltr637yy5c00586r9q5mfx8ldgw8r5ye2cehpncygupsmjxjwh
    lastmodified: "2026-09-08T01:30:13Z"
    mac: ENC[AES256_GCM,data:DycOzRS9Krg6ynZtj2jYaq0rhHN1wXuVXN/nRrw7fQg/O6WRn7O/CaRujFHhP2ndnQcY5i1VAMXMLGUhcJoEb6SGZ5hzAkG95RFgvh65d/CWmq9JCDadqXJ4dfk/gBuQ7lKaqhwdO1+oiS/hHtRCfgWR2Uq0zxguiqltOGuNDXw=,iv:KkkdfQi/vqBjG0mIpfKD77N/PN2DHS6+Heqot5+V+Wk=,tag:b/aBeDtbV3UOqbl40kjFUw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
