apiVersion: ENC[AES256_GCM,data:OrM=,iv:lzfMTFsLjeHAetC73dqEUvh/voxAiCDQLDF6cWRgrxg=,tag:bxmQ4M330uO6Wc0JlGXuZg==,type:str]
kind: ENC[AES256_GCM,data:aHxEtRDk,iv:EdmBtElCmuuHXyC4lrki1/Xs4cDu8ninwPQ0CE5Oq0U=,tag:RO08eg52bC0iytX6HhcvZQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:u+NBTidUGgt5wcNe5GJGjw==,iv:kkJRTWSwWmxLoAigXKRGhM3maQOjQaEfPtIgLMIohkA=,tag:twpl7KWK1J3VGsLPS4MrZw==,type:str]
    namespace: ENC[AES256_GCM,data:Jy2oCwiaZc60gEY=,iv:Mk+404XOWJ5s1FX4wzMwohC6wRxjrCXsUbS+H7/dDGg=,tag:RBJQv6YciYMfn1zKhrynbQ==,type:str]
type: ENC[AES256_GCM,data:vwlElbyE,iv:zygqJyHZRqd9Rbb2OyM0vEKW0arh+54iBVaF5Z9JLmA=,tag:/wGOlbx4YZg39cYNi34opA==,type:str]
stringData:
    LONGHORN_HOST: ENC[AES256_GCM,data:S1kX17M4x/hq/UKD8MJuenPp0A==,iv:UJOWenL1mox8MjOhFTq33IRffdRnOqMGFCGHaPKRwqo=,tag:BzlHmYNbYLG8QeOsMkgHlg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6U0RPc2pOMWdnU1NqaGVj
            b1BWRm1HZHZ5bnljaHJPTjUvbXNLcEpxQkg0CnZRUnZNTm00emJjV1hDdWpWWmZj
            UCtldkNmU2pmVlkvSWQ3L1BTUHl0YTgKLS0tIFBuNEZVSFloZVNUaDF6bnp1NXpp
            SkJNazJGckpuVGlzbEJ3VXpoa1N0K00KfjEclP1yLczDuPOY4PXutZJ7h6PaKbmq
            uUubE4gm0qCvebmElqehkkdi1mQc8tO15UoqLDTh9zh4uPTo7GJvEw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jxtdxm70ltr637yy5c00586r9q5mfx8ldgw8r5ye2cehpncygupsmjxjwh
    lastmodified: "2026-07-16T03:46:39Z"
    mac: ENC[AES256_GCM,data:mwRGwvrRAvVE/PQ451McurM5ye8QsG0NbWrrEyKZhIchvNb/ASgvoTR8+hV4NgrqGuP9SWrlevQjUh03U7CinpNS7LsfG9oZDDBDGDMGse7o0hqDTRb/n1/J4h9b+NaetKOzbGFhKeWjkzgTe+L5n4Mxjhc8YPHCLYafHyZ/9cY=,iv:og44V9N6vioZ5DjBdw0hf1n+S1jBVNyHAVC2jDOmHBE=,tag:YfymGaJwMSLrZPgdHVfaHw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
