apiVersion: ENC[AES256_GCM,data:6Rg=,iv:IbVAzig08wVJafn6YfpxCypgIZc0cILAgWxHRMnHIvU=,tag:lMxePxpKF2kv9BMrM1SbTw==,type:str]
data:
    auth: ENC[AES256_GCM,data:2IRSRmVw5gl6Z33nuZPfi5QyysFwlHJIIjd2xMRTx0z27/OLKnqrqoe7yj0IUH0VOMY6+mOqi/iQbAIcc5MUVU6biZ/SNM/m/yCR852NVDF1mmcZbaDOR5C/XNl+4r6cKAvwgxEsesfAxSCSvUHEhQ==,iv:d7RkU4hlT6yyF6QBcIgRkrC4ui6n2vCrFmCi1lRXbdM=,tag:DNbaj8Ig9Jes7l875fgnvA==,type:str]
kind: ENC[AES256_GCM,data:bucQyXzZ,iv:SHocQT8YmSuDRwftMss75opnrKdoJg1z3AKROSK6UJg=,tag:FrM7T50otAyYr/dgwStP0A==,type:str]
metadata:
    creationTimestamp: null
    name: ENC[AES256_GCM,data:JpOgQHYemWaLfIplStdEnwYTWw==,iv:YRw4wKugFUJOUH+krK/KhtMxSunUj5RqrmCPnw/uqog=,tag:vKFeBC4Bhmfr6vJ1QbZmcQ==,type:str]
    namespace: ENC[AES256_GCM,data:Gn/01QecK+7pAi/ph+lD,iv:IrJhFz2r01qYeee7voVQXpzWpiIBceUUGQh5HE65fUg=,tag:BLNOa+DbzMvp9zOasmlFvQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxWUlKb0FFWGZTR3R3Z2R0
            L1F4WktyN0E4Y1J6Sm5rSk9OTDIzQTBGb0hNClJkT3ppc3BhenplSEdrSjlQREtz
            TnJ6YmdRUVgrdUJWSitXWHZiSEFMQVkKLS0tIEY4Y3BxS1JXNElPVlgvOTJhQlZZ
            OHRMTGluQmdVcDFBZHE5U2xXQ3B6R00K8ER+BAlj5KDMdDxUIZwE6YQkxdQ6T9X5
            YN6Sqb8Ms2zJjDv18Vzc25W+XMKTf8wPD5eOPNxRleZtk/eAEPJ8uw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jxtdxm70ltr637yy5c00586r9q5mfx8ldgw8r5ye2cehpncygupsmjxjwh
    lastmodified: "2026-07-18T07:09:43Z"
    mac: ENC[AES256_GCM,data:9sLw2PSgQRKnAbWPq/To9QjzWYjaXd2Wt+9V/OkednDAlAm1+kyk36M2m3WJne/b74UA5b9kanvvowVDDLuIsj+cEr6YQr/TAGP+lk+CsLBzYMZKT8L8Tok5wb216JDC06dLh/NNGggKFUScymH0JuTzvKV7PTvrJHzBT4tmUsk=,iv:BnF7Q/57DxSm4o19h4xbbpK4bvIOZqy0lYBQ91q7V1Y=,tag:x9LAw0HgAIVtmYPrhtpfKw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
