apiVersion: ENC[AES256_GCM,data:PkM=,iv:be9BbbxyDY8fBQiV4W1j3pybIFO/aHiZ8bQHxWT5D+o=,tag:usEdYxDv93I2J021qYwgzQ==,type:str]
data:
    CIFS_PASSWORD: ENC[AES256_GCM,data:18NevhnChHqS2Ej6DQwt65yPEtAJIied5wpE+exoZjosNg0RvCg/DQgPjHE=,iv:5OF4amDANCO48X8qzExkdJJOp0onof4v6mEPgpdI+cA=,tag:WvWtkpBGgp73NTvHSQzeug==,type:str]
    CIFS_USERNAME: ENC[AES256_GCM,data:ZVlYK1QSgeM0F2kD,iv:t6t099S/eleBX5V4dlaCPyen6lI1C4Q46fWCURHp5vo=,tag:cjaYr+5WYCGi2Vt/+luiAg==,type:str]
kind: ENC[AES256_GCM,data:fKKRjTsC,iv:V6KH4Rf/T7ugI1+j5Sgl399PMESTvzcasOsT8HNi8vc=,tag:j7f9/w4JRZNML5azGbPW1g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:LK5C9xpzP1mkx7MLhuWl/uJJVzDU8Q==,iv:U/4r5s+YC7aFDmUHFe94FibWIbaZdiKUukYM1PWZTfI=,tag:Ld686HZxkZiM9QyhiHPgUw==,type:str]
    namespace: ENC[AES256_GCM,data:6WfAAtJhA4EcV6/ARexu,iv:11s0wQwCN90EZEyuzH7L60xyV+Ym5gvaLNEj94ZdMcE=,tag:go2dnb7MGSRMi16nr1K0Gw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmNmVGTzdCTUg3emNmSmVQ
            RWpac2prN1Q1TmVlcGVuakFqYjRlVWkrcm1JClk0cjd0WGdiTVpFdjJ2NDl3S084
            L0NwenNXYkowT1FZb0FraTYyMmI2YWcKLS0tIGFuN2VUUkRqMXE1WHBpNU03ZFZQ
            dHE0M081TUJkTGJqMHdKZzQ1dGF2LzgKFbpVljAfThNHFYLnUTgM20izH5XYpH8Q
            tjkzWDC/7bM+E9AU6D7fsBst5vJNekvEGNWLmLmkMPmV/N5GpEO3fw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jxtdxm70ltr637yy5c00586r9q5mfx8ldgw8r5ye2cehpncygupsmjxjwh
    lastmodified: "2026-09-08T00:37:30Z"
    mac: ENC[AES256_GCM,data:pvI6jImCX6E0UafISGkEAEzFtsiEv7pjcbuxDsfRSzwytHGYflFanKN5SS+zs4YOnHGLfvdINIBpV5NAatgfps35Eh5nDoI5BIdfrLcCZtV9+9qY9RgHuzf9Dnr9fumxUhenJgP20lzsCds4LdeYgrmm97+PVsvujyinY+kAtJg=,iv:hjclORv3c7VoJOjsgT4f7oN+frMnZ7FC3SmUSy4B/wk=,tag:HKt4lJhGcl2fg42uBhKkxQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
