apiVersion: ENC[AES256_GCM,data:FhY=,iv:HupmWWBqxYiQDT2nyhHpjiUHcLX6BeQWvBLTlWnIDYI=,tag:GfJq1GkMoZ81ZiuEMw2YMw==,type:str]
kind: ENC[AES256_GCM,data:wy9ofBkK,iv:f99hCWtXQD/SHgFMu5D83nA/g2WbvH7UqeVQlbI4LCQ=,tag:PC6v2HcHYDIbg2DQvxnIyQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:KddGL+vox0aUwd+wlFiGLXRBmA==,iv:man2KXR2WwQl4ufN67FbY1DFxtrwHEEg/ljZm0TWXsk=,tag:IlmRJAIapz0P3ZP+suUemg==,type:str]
    namespace: ENC[AES256_GCM,data:VTDowyWYSYggJycwIcrL,iv:1tVw6xlrk2Q5sJFTtUKSbgF8DK7KisS7tHhcSGid9n0=,tag:p+ow0yIs8GDRewVrAXt9Og==,type:str]
data:
    .htpasswd: ENC[AES256_GCM,data:Y3hNx4F8TKGwycLqUm/NoOpWtIC+Qmtr94SvOXdyMmBObpyreCEQY4n+RTCTXsXR2C2fBA7qDNzYLW1nOyh/oN8umpAzgkmWljdN5Q==,iv:H4xVYKpgS50ufxXpsjYRhtnPMMSmnSLg/t8D3PzAsu0=,tag:s5vZNqLFGTGX70LFCk/Kew==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrbkFBU3dPMVEzdVovdjNY
            YjN6OTc2Q20vUmlGbzBxVXNNZTZlWGt2aVRZCkt4b1lIc1A1RlFpdjFKSnB3bUFK
            ZDlPb0xreXJMdkFhWTVDdDN4RGRuQkUKLS0tIGFuY3RkejlaNXpiR3YySmtGNjcv
            cWJEeks4VG5PaFRzMW9EMmoxaHdNaWsKdGrugcoc689vdPsASZL3+Cz4vveUyWZ/
            ga2dPPufHafFUNJCbqJ6FxnSlyUf3uQ6I2DjwHjG7bM/484YXQ395w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jxtdxm70ltr637yy5c00586r9q5mfx8ldgw8r5ye2cehpncygupsmjxjwh
    lastmodified: "2026-09-08T03:29:06Z"
    mac: ENC[AES256_GCM,data:ZhWjiegbU8NYe7lCuO+64aioQ1Hr2ChhZuVc80sTfX1oo2EOqQ5A1CbXJiwBjlVbJTwQAtexn8TfD/KYf2BZxwmgjpSJZ43gmVX9/PHjplPziDkgoufL9i+XhR3ri7foRmCWpwIqw2D7tSdzkR0FLoWjFECIW5M9mIk1QnqRCEg=,iv:L3CmASGWZMOufJVUBXYFP0xbtcIpNn0kJll2NF46nSw=,tag:BqbondctcOKZjBWHDImvSw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
