apiVersion: ENC[AES256_GCM,data:DBQ=,iv:5BwcMVWcbn5cAERsR8+RRG6RjsnFljpWVcVwfojiU68=,tag:pq4UbYcUZuEGAHZsVp0YnQ==,type:str]
kind: ENC[AES256_GCM,data:J0OKdRrj,iv:qWKFJeYpjuvxiX4aAr//2lGHm2uWyOLslvLHkxQt/Go=,tag:6fwSl+cH5e6jf8nWGly3fA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:UIxU3DrmJz4KgjRwBrCQAKMYJYc=,iv:vCAu1SIIoFyUsFtUucDbxCopkoHKNarlYHi6erfzNvo=,tag:E5iqAMOq3Fs/TClGR76Z/g==,type:str]
    namespace: ENC[AES256_GCM,data:NRTuwgettyU2cbk=,iv:1o00pXfDJnmWTClSK+Pj4ToqEUEfQWVvNZBA9gPRr2w=,tag:kJEFNiY5N29j404iaF9aQQ==,type:str]
stringData:
    BACKUP_TARGET_URL: ENC[AES256_GCM,data:yWIl5/0dEU7dtkaGVHhBtLhF26KgUPSwz4dmTQfeL7rOohfi,iv:ophjBaAZQYnOUWxPJdPGLZDrmg3AZHfD7nM+Q7XV87Q=,tag:qc5+fFLTtysAaRIQDPsm0A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpQlhsbjRTQ2ZZSkx4alF3
            dks2SjU3WDFZZ2NHQVZSb2M2U0xQcmUxbXdVCkh4UGt4RHFUbkRkR05TRyt4SGhE
            TTgxWmkzRE9IU3JKUXE1eGFiOWxGQVkKLS0tIFR2RzFndDF5SkhYck9XaVBvMmJq
            WHpMd0VudGRIQVdRODRDQnByY2pLVW8Kebte1fSGYdQM/pbRADdsYpC3UiI3F+S2
            K1+KHiKFeB9pK8jua5qPzJ3OkO13YM+IlV47TlFSqD69Y4IfGvR+Ow==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jxtdxm70ltr637yy5c00586r9q5mfx8ldgw8r5ye2cehpncygupsmjxjwh
    lastmodified: "2026-09-08T01:01:04Z"
    mac: ENC[AES256_GCM,data:jyJfcZCDKwcP9SiBuDQYWqT/dXX6iqxl/YOXSWTuNK0kLLU2vZxmwtIbmjPpP+IHb6tYfcKiLRdpMFtv94BeEmSRg6Bh69pJcjOWuWwyqb4kwDm6PE/JwVu5AbRnnzXfuRhbHUnBIntKMyc2Vh/BTQmj9iEGLw5Sbztmrh+qYi8=,iv:dw03N0KsSXWjNZ8zEszvoR1osS8/99OtKCpmtobj5/s=,tag:pBApTiXs7bV+Rrnw3EUTBw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
