apiVersion: ENC[AES256_GCM,data:fvE=,iv:/KVmCpiZeLXo6UoZORftD56thONjv5OI6/UkXNJwhI8=,tag:573UsrLjwi30d2dfHUEbyw==,type:str]
data:
    rootAccessKeyId: ENC[AES256_GCM,data:TuefmTXPAzg+YMtk,iv:PdyTbwXRWrx3J0bOjriYqcea1I8qw/Xa1Zpt0YBfGLg=,tag:NQ9jSfOCngoTxu367/rKGw==,type:str]
    rootSecretAccessKey: ENC[AES256_GCM,data:dbCyqhrxBx/Ef9yenWQe9X26v88Rj3erZsv4vZF7hGDjatmQ3iB2x5JBIUeQKqu4K5/DtlaWnkw=,iv:tfJ9Rrl3Dxi5LCcNf+qQRtl4kpYlzhNJlJB6VoRm+94=,tag:M47SY1+KwCyYIXsoXLkXRg==,type:str]
kind: ENC[AES256_GCM,data:+cdaaWYV,iv:0tvdU1viU2CNCXC+n6+zd4ILVdd0WbluzXYha5Ro1X8=,tag:WbQz3VqiBlmvP1pImqyTfg==,type:str]
metadata:
    creationTimestamp: null
    name: ENC[AES256_GCM,data:6t6G8VljK6k2czwa,iv:j7yQ07plEG9MzVgxtDhziPItoHZGzT87p1PxlKF8cFw=,tag:nvy0cOxI6CizZ4hoQSuMYw==,type:str]
    namespace: ENC[AES256_GCM,data:qZ6/G6o=,iv:szfkk36GXezmnqB2D2y7XutKiVeR1JHlkeL5/MhMYos=,tag:lzzRMhRZH9nntfafgcq7cg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBydEpMVjJNUEN1MDhvY0xT
            aHNwMzNtaE1WUm9XRTRnSzFSMGllMmdYSEZNCmNzVW9KcmR3eHloRnhOQ2pndURv
            WW5lYTBYN0hCZ2pQSHFramdWbEdVdXcKLS0tIFNPMTh3b3djaWRCUU90RXVDUTJD
            VGZidkxGVDFjUWtYd1NadkRvR2V5RGMK38xOpZ67CmTOge7fwxiXQkrUMoD7GPRO
            avZ7JIS8ZNF2mXTtyKZ4ZAVEzfNrKjh81RErks6badRwk6CfOWoIFw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jxtdxm70ltr637yy5c00586r9q5mfx8ldgw8r5ye2cehpncygupsmjxjwh
    lastmodified: "2026-09-24T03:12:41Z"
    mac: ENC[AES256_GCM,data:Y+PiDSJOxghn5PLoVFjEji8ldsYDHT5jf0OVVimXRSmGYyPir/E+nf/1+hs6TnbJBm9iDLKPq+330Bk29k3NAvfBoYawc1QdL+LjRPyumS7dwH2lQYlJ7C4yRY8a9TVogj7xsmGcrWiMYwYVS728K3CWO+/5stk+mDiMBH+jvEE=,iv:wPd8CN9/WYuTu1oEdzQ5sb75N6jHll0PEdtgDUyT9b8=,tag:wWRI4VzIpgssY/taB6qklQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
