apiVersion: ENC[AES256_GCM,data:sic=,iv:N5f9Lvh7DPkubGPjwM884zxktZw91wDJs/c7nsUcpoM=,tag:0DDqFGOdhhyxeNplMFP/cA==,type:str]
data:
    accounts.conf: ENC[AES256_GCM,data:MmIqGOlPdke3y9csrIBG0sX3PjDEYyCBE4s6ecjw7FZLVpL7m2eJRnUhEFXqe0tUYtppjUbPae4d702z+Ikhw2LnxuemfumN,iv:rECPvtXva4/Og8Txhoqllam/atgdI9TWTYhUXNK40MI=,tag:NS5w1iEyJGeujDiScNuHBA==,type:str]
kind: ENC[AES256_GCM,data:C7G/CT64,iv:zcpXceIv3eXszDvqwoCdVjuE83Vj9A3crnqkOBXQLKw=,tag:/dWpTE65Lvnm7DW+vZQs+w==,type:str]
metadata:
    creationTimestamp: null
    name: ENC[AES256_GCM,data:siTyyx7jsRyEw8La6KtJ0Iuh,iv:mqJ2p3UwdTDlTTV96B+eghirjDEst0bHHCQH6OiGQ3E=,tag:AEPV70XjhaPOqvEZDHgO+A==,type:str]
    namespace: ENC[AES256_GCM,data:PtCwuw==,iv:ZyQuIYbIKXBaNoCNk39wmsBoBhwvbnjJo1RHdhUzGiQ=,tag:fd58KP8f9of5M1z7xBH+bw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVL0xzZlUrZWt2RnZuY2p6
            a0xWK21jbGlwUUcxam9UVVB3S3dhODgvYTJ3CkNIZXlTVVhyRHdJUGw3ZU1zeTFY
            NzhjQ2NTdER4RFY0UGIydGRLVG5VdXcKLS0tIFc5TVZoZWRBRjRkK08wZjE3NzU5
            b0FtcTdUZGFwZElmUHJJZnc2bnZrZVEKCb7JEnHIv5c8KZ0DZa5yb9+IhLAjOki1
            V2f5pfetsJAhGf6CZkXyZpGkXInb3icH56Vr4cgsHSi/xbR5tln84w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jxtdxm70ltr637yy5c00586r9q5mfx8ldgw8r5ye2cehpncygupsmjxjwh
    lastmodified: "2026-09-21T03:12:21Z"
    mac: ENC[AES256_GCM,data:Kv6rdSTJpegs24RCTUpxa/UTWopuzzEKdbHzt6VWS/L/e9j5zbUL3U4EsBZncdlCohiQFjICoWWMHwAFyItv6q/6sit3uBQvs/zEoLh3tbJxBE1uQcEypEu9OG0ZA7OWvMHYksA2A5nMPW25cf5Ix4QkH+63vPsYW6l0QF+eTgc=,iv:cr9XmcbhBylEbfQz8J45upYJeDgkAJ0K/tAGqeu5s6s=,tag:2Cn5V/lxc6R5ul3U+0/f+g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
