apiVersion: ENC[AES256_GCM,data:oQQ=,iv:+V0K8a2T/Q+zVHrwP8z4ibP+kDz2CiaBIJbiBibBd0Q=,tag:F+ZG0Y0dM3emvP6RoEzG+g==,type:str]
kind: ENC[AES256_GCM,data:6pN26h2U,iv:+Et76O6HrL7qnhStVTBL9XDJRhYBJvli3J1mF4kJtac=,tag:CXL2Zf3l4YuJEgwQeQxtJQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:XwOSIE0gcB6e0w==,iv:bVeCia4sdktvRuua6KDSd0nxHFKvc3C6cpUMkzs0Rjc=,tag:v5sJPVW7QSM3dAzqeaI+LA==,type:str]
    namespace: ENC[AES256_GCM,data:eVURAg==,iv:PNTA2vK1Q75Xdt6jdGRzFY3mWVqNh44+ZBgTujS+MeU=,tag:RSQMuWtkoiA96PvFIfIGxQ==,type:str]
type: ENC[AES256_GCM,data:MUSdGlXi,iv:8i5oQqRObscNg+u24DbISBZU4W/rE0pNR5SgfFDC0l4=,tag:RemrqIY/gS3cxRMm/O7k/w==,type:str]
stringData:
    claim: ENC[AES256_GCM,data:0UwjJrcwK0p4btQQ+MShOkra40vz1DSzjMw=,iv:+IH+KD++rXl2Dxz9orfkqdINfSwofTsYWdpdFUbWXKc=,tag:kbR3ELU2gdplkx8vBykzaA==,type:str]
    advertise-ip: ENC[AES256_GCM,data:vhhBvH7+9PJ5+XtwNsoE3zyabR5sbGNLJIhuqZwk3G1YFWyFLswExgCk25zgUdkFm+5t0IJ6zhF3,iv:MBQy6BJD0ou8RBPiVHl5AVAm//G4ppiguHTFDQHRl2s=,tag:0fd390va4JJJeyPQayGFhA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3TFNTQU9McDZxQUtuZ1BB
            Smt1Q2RoSEZrQnYvMU1yL1lBSXN1VFc4dTN3CnFVbXJpbVBmTWFQZVpjMjhBUDFv
            UDV4T0JSQzJJM3QzSUEzT0lxdXAvaGsKLS0tIHBxVjJHSmJFeG56QW4zeDdsTVZt
            cXJsbHNrYXFqeEpkbUNDdUpBa1haRkEK5+mdO5TJRInSA9CbhhELDIJmiYcljY1R
            0A/0832uPZe2xZ6YYy+/A6u8cwQFG1F5tRJsKUD3IyIzU0E+Cith2A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jxtdxm70ltr637yy5c00586r9q5mfx8ldgw8r5ye2cehpncygupsmjxjwh
    lastmodified: "2026-05-29T20:51:07Z"
    mac: ENC[AES256_GCM,data:+8rgzufjlbO0FZFYPiC/r4U8yrab8Lik/CyecJ8t/dei1zSAY89THYu2cSOrCiSbcXYcEsa1XmR/MBdRddUm1nvwRG5Ir9PPyIhA4g8fdjheIW5bogdfHBDuZlFMOzGpdSddpSsjku6M6HWUJ3PyabzXXF8Jm/zuYaWayoXrJZo=,iv:yao/MyxS64GmC6s3izwsQkYmtwZxJp2+VxqQrG+Rsz0=,tag:aFuDG8HDeKXcBk3RabSxVg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
