apiVersion: ENC[AES256_GCM,data:3cs=,iv:LtsDlCUXRfej272rqXcJMouXuGrbqqwlE93puHh9qPU=,tag:HaiYkD1zaEtbnTLMJRDSFQ==,type:str]
data:
    CPP_ADMIN_PW: ENC[AES256_GCM,data:F/EvYIjtW/tskZvXvinb5UCM/7CugwVM1Gdohw==,iv:xt0UTCoY1JzrqUAVFLHJo5O4nWVCZKHP/+U7w6RxguU=,tag:n3HhVWAacstc/PwODfl+Ow==,type:str]
kind: ENC[AES256_GCM,data:LYvBRgeL,iv:ZIUL1tI50+N1mYVIk0Mb++xES/TdD4DNV1oCMNMZkl0=,tag:JleHsFwlmFLeEJOtqygewQ==,type:str]
metadata:
    creationTimestamp: null
    name: ENC[AES256_GCM,data:2Q5zf6y9846hLJ7Y6bTn,iv:XJIi3SKsXN9qXZ3tMH81q/AnOT3WG84lfiVaEPTOPT4=,tag:U3uzxvgseJnPT91JpVpw4w==,type:str]
    namespace: ENC[AES256_GCM,data:PxH1Ow==,iv:ktXodSUNH38KEdARH2aoWD+Ub1yFBkKFXu4NLp1tUO4=,tag:L6rU3UkuoXnBMtekry2pRA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhWGdDNkk1M0dJWEh2VWJV
            cHhwcDAybXhYdjQxbHFNRnZ3OUNUUEhhaHp3CitEVGJ4Ti95amNwSmFtMFM0N09O
            c0d0OFFjM1NqQkl6TmpxTUtnYU56SUUKLS0tIHFmVFJLT3NnNGRwTWdVYytWdXp1
            emQ0ZDRLNmk1ejBmQUkwZWtrQ3dCM1kKU3hIFHfHrFirIA66bYPRhWKHtqcxqpLr
            Ac+j6CbaPJBjmb7EkM02SnrQNSU4zjh0+9L4ONrzXn6d+kuFjzNkrg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jxtdxm70ltr637yy5c00586r9q5mfx8ldgw8r5ye2cehpncygupsmjxjwh
    lastmodified: "2026-09-21T02:29:00Z"
    mac: ENC[AES256_GCM,data:sLNthLL42KfsBFExfWIjLgUpT2gwqv8WvA0BIE2xlAjtVb3RDoGYnQs/BBRNj5HnQC1Tv3r8osNwH9M8Km1yq+bDj9WWhUxhzkagWID/IbGyydWd2wFV/0vOyNFLY95ED+Q58hY3g/J4UAGMH8DRiIb1S/ZpK7aCBBZwc+Xsvzg=,iv:Y/q6SGNWgoK489nYkvfY8lCaEWUtw0Oxe7gM0s/yli4=,tag:3ZnsWDj7+NUfz8QuuSW2uw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
