apiVersion: ENC[AES256_GCM,data:EVQ=,iv:UWNa3f+f4sMMHcv7qbpHPgMboeONga5oFTtB71Fu9qs=,tag:7eOtpXZTdjxbvLmUcNFCtQ==,type:str]
kind: ENC[AES256_GCM,data:y+4tGG4m,iv:hiqKaVncwx+IPzbVPgYXBHAl6UOZipAWA9GDEQB9hqM=,tag:Y2rafhwZ8pEoozzKD1OQew==,type:str]
metadata:
    name: ENC[AES256_GCM,data:wp3wdk7brm+WzREPQhxjuqIxhMLL,iv:mtbuGs3cRopxzCcgzpsGEMZouTV8Gjtzpl1lTryKEoo=,tag:iQp9w+kY7E7AcdUmadZIIg==,type:str]
    namespace: ENC[AES256_GCM,data:ao5JeqjfM3FiFBk=,iv:1b/ZSujfSgtcGkWIGerbhH6064lL5Xf4z+wx95uylKs=,tag:9BiHViUlDm8QivnaZBfXIQ==,type:str]
stringData:
    FILES_HOST: ENC[AES256_GCM,data:O63beuPxMz4n/mwYbH2XkA==,iv:1xzgBh3n+3YeLJfHWDB1xaF4kNVjAJSQpYYBruOf/b0=,tag:k/lUSb0/crTJCNE0kxie5Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQdjFVWnlsb0RxbE9NME80
            YkJWSjhKclcvYW1vOEJMcnJYNmFsSWhTaG5zCk16akhLamU2Y2VZTERjY2RmVnVu
            WlBublVnVVo5UUVHbWRyUHF1SGhVVWcKLS0tIFBxL1VCend4RVYrVUVpdDBvWExE
            UUlFc1RiQUdDRkgxdjBWUlFmOTNvYlEK2rhk1LNJ/QYg8de5x7WfI9VX26CAEWgH
            nekYeDQ1Bct8nsjlbv0NIvHOQyFtORAtzqT3nN04ZRjg4CA+yVTUCA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jxtdxm70ltr637yy5c00586r9q5mfx8ldgw8r5ye2cehpncygupsmjxjwh
    lastmodified: "2026-07-18T06:17:08Z"
    mac: ENC[AES256_GCM,data:fUXd1iq5Xa+u0oU+aAPxT1CgLt6J/uk0QauzCZlaCj5VFINAm1bXgNI2SugmgIL45znujHBH2reXLgpMG7m7ONtG4RAMgMOVF7I3pGT+i+dGjxmweo5ZyR/j4gY1dnn2rb+TMiC+oA+ceA0rEtobXIMSpWWR4NYQ2ZeigDF/+gI=,iv:Uu66JQxX1W+ir0oRbtK0c0DShYD67T0eBaRYVP5v7wo=,tag:bFeAsuP4Of+pISfIXRE63g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
