apiVersion: ENC[AES256_GCM,data:wtU=,iv:BxOrZlbDeMwnkUnApeSCQ9QOp+tXYhQOz0x7STNmqYA=,tag:1FwCs/2EKTihS+v/vxlNMw==,type:str]
data:
    CPP_ADMIN_PW: ENC[AES256_GCM,data:NdBQG7+AuXebwUISBEvm/wn20nzGIecKF2ZSUohpqKinKCdl6vw9gIZEn3Y=,iv:PKn3gOdtf+xOTV0Hn864bZgSdE4ITdTwMeapChV13Ac=,tag:Kz1kfGOBI2IIe4nN/Vs8tw==,type:str]
kind: ENC[AES256_GCM,data:aviH3qZn,iv:ExOhFFKOqQLFH6RxHRL1+A+mRyWlPVj/rNwIANfKbVY=,tag:nv9BhDS5Dke+DYe1MwSnQA==,type:str]
metadata:
    creationTimestamp: null
    name: ENC[AES256_GCM,data:jJ01xVgGDVnv2gY5XGr4,iv:ZCHxoqg6VdFMvf5Vo+MKSHwE2Srz2H2mB94cLqQJXic=,tag:vCYdD0ealrwB+rtslC2N1w==,type:str]
    namespace: ENC[AES256_GCM,data:OVUOmg==,iv:OXQvmeCQN0PD/x0do3zlBd84PoQFuO3PW7KuoPiT9sA=,tag:41PqQqxLVEGAFmxHLD3/gQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQQ1NiWTZtRnBHNFlDQ2w4
            UnVRVSt5bG5zSTZqR25ZbnN0aVFQU1lmQWxzCnA1L0R2N3ExeHBDK0JraDc1WHZI
            ZmNWbE5oeWVNSDV5dnVRVWQ5bElTdUUKLS0tIE11WFR2WnliUFdLRDRNNWN6TlN4
            MFBZR0ZHU01ldlFNeVo2RExsbC9xbUkKPUkD496mdKItRvksCY+08u0+df8SW5hU
            0sf7JCxF1UwkeovS/Xw22/4+ZAQqVm1u3SbmbsFiOf0Q+shF/28BIg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jxtdxm70ltr637yy5c00586r9q5mfx8ldgw8r5ye2cehpncygupsmjxjwh
    lastmodified: "2026-09-21T03:01:49Z"
    mac: ENC[AES256_GCM,data:ZgGaJYA9nywcUBQwjqfKqdb3OKNBOcdo7Vi0M7yfyvukVhNbduHWwarnAljHi8TrGf8mATxyzrjFhKxXvoZC6Ekiwhal2kviL+6TBEBsNLnxrUfODb4fw4AAzK0NyW+i8vtTDLpZ6j+C/xF7IceMKgWPazmh0JrE/Yk9jzyusMQ=,iv:PRiv3bTwL+6ly2Q8OxRXK3ZqfNsgwLxzUrVHzEaRwqg=,tag:tT/LqrHWOL4NhCkGa7iQig==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
