apiVersion: ENC[AES256_GCM,data:yqk=,iv:AeTViB0mAXSdEFjAiz/mfQR6fV71bgST+9K5DLKusIE=,tag:O5cYd8fP5m/oFvYrduHNyw==,type:str]
kind: ENC[AES256_GCM,data:LYMx/Z0Y,iv:f2rEY03aVb/Iug11DNodfeDmptuEgXFjhhJ/dVowNNA=,tag:k/TcM/b3Ok5JsJSt14Ib3Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:WlPZ2jU+eISOgtczD84=,iv:pmZSN7BFipE4kv2tjd9Z/dysGVP8A4LJoH9YCNuFNBk=,tag:vNMcOOAzWyHNbMcQ+K15tQ==,type:str]
    namespace: ENC[AES256_GCM,data:myZqWUBzi59I2zU=,iv:SZ7t1wbp61fAeT9skWLysblq9j4NFwNw1mMfiBPe8wI=,tag:hf00I/byRmkQxDrrcRbB+w==,type:str]
stringData:
    PLEX_HOST: ENC[AES256_GCM,data:uzfJ07ur1a18EMLPi/v/,iv:QzoO/dpGRzbhfRffjqDkh7Pj+WflUCWWScBVohigG8Q=,tag:rylt4YXmwCaG/i1gVAI4AA==,type:str]
    PLEX_LAN_HOST: ENC[AES256_GCM,data:XgzO7Rjjbbiy5Yp5GmVV,iv:N7wx1cAhClc9ss6TgHwM3yK0b9G4qCqDx7MG0h98BeY=,tag:70ZDW5EAuNnoyEz9e6JopQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLTjBvdXFxNEs4WHRUVlZa
            OWlDS0QrT3NyVm9jMHptK2VwZm9XMDY2a2lzCmtuaG1IT1czREVUeXhSem4xQWlW
            OWhhbHFhZkVoZGpicWtKdjNad3dzZncKLS0tIFA3Wnd3dkJ6MWNkdnl3K0JEZkVU
            a04zNTVyWTA5Z2lqNnV5MTloeDdvcU0KZTaMpoj/OgEPLEryLzqTzwRNifrX18D6
            2oZgjWvSNh5TUibIBGFbvzQCyPcDY6R0jFxQwBcOacfMd6mVMJx8lw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jxtdxm70ltr637yy5c00586r9q5mfx8ldgw8r5ye2cehpncygupsmjxjwh
    lastmodified: "2026-07-18T20:12:45Z"
    mac: ENC[AES256_GCM,data:1UUDio/aZ7GxjxIykG+HX4okCc+psH6olq4LEaSIc0rzqebOl8NkDJiEeYb6z/2BnJMQrPKNoNu2gI+zzL0gylL8lKRiOB+eG4nTXv/EG2VW6mEoqgFWsRQ7XQ1xSdOeX5Gx8E7/P6RpJO/Bl4ZK9LMYATMY/i+na+4nOrTqocc=,iv:PZ10rthh99nnaRfmYGKos+QUaY0ZpQydPKCfRdiG2lY=,tag:SijPa60hTGF5NJN6FGswhA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
