apiVersion: ENC[AES256_GCM,data:mg4=,iv:VBAlQk7c96zXOE00of0nP/iTuhTXRj1NkiqVM2uCQdE=,tag:TPbm7DcLefcXSc8Dl3vsrw==,type:str]
data:
    FB_PASSWORD: ENC[AES256_GCM,data:EdV+Cw84U3pclZIvAX6Mh5gQmNDQ8R+dw0xi+jcW/JTKZTan6x+U172mfWpd76fUJ5GIRSfrbRyOx+mfuDg7ZnIF/20jFSCDjEoPAEoLO/Y=,iv:uzqPeEP4PIkFu99ZndBr3O6qYULscCLjSdj9BfYVL9Q=,tag:VbYmEcLffzcaAGn3lpJnew==,type:str]
kind: ENC[AES256_GCM,data:DlheXqIm,iv:FJXouL+UXm0YJn4eeo2VLXh0zIU+TM77h8GpDqFWW2k=,tag:D91b/1Wun24PxEFtNY6T3w==,type:str]
metadata:
    creationTimestamp: null
    name: ENC[AES256_GCM,data:zItI5uMj8g/XvKMcyV1IXEI=,iv:faHBR/aMoNot8yAOQmsrsiyQGNsGKqGJE8edeIqzqlM=,tag:Q63RDrmo+adC49308EOp/g==,type:str]
    namespace: ENC[AES256_GCM,data:gpqQ4w==,iv:wBe28SEIcj52ij3sC8XM9dQWgd66jciWLcqyPP52zuQ=,tag:09v+RVd4MyomHok6PX0SUA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBialJ0aHRZVkpyV2FlZitt
            N1J6V3E3a3VQTDF2MzhUdkhIekM2WWJ3UzFRCkw5VS9ZZ0duUmY2OTk5WGtkODFk
            blZJQ3pBM1RVWXFOVFBhM043Wm1IaUUKLS0tIEJCTlM5Wnk2R0pwMWx0OG53OUFi
            cDY0QW9Mb2lhZCtCYThKaXEwVDZPZDAK+W+P2RDARF/RcJCzxJKxtE5h+tm/LcmB
            63pG4c9aTd+T18HQUmCqnafJWCZAZ/AG6EGYQR8oMCMjleByT8HUXw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jxtdxm70ltr637yy5c00586r9q5mfx8ldgw8r5ye2cehpncygupsmjxjwh
    lastmodified: "2026-09-09T02:08:23Z"
    mac: ENC[AES256_GCM,data:JyaliTgsU6f12GwnsJoNvmiaVN/vRE10/zjY+DyyOJt9D93Mgf6RKj5ISO2dpg7S+tu4+0uodZYbuJkex6KjYifQlBePqcJ8EFdkoLKjcQFVymXuU5U6wqdKkI9s8i9XbExdoJYFuoByqRTGc1dU3dXyxW+omQBzQewUnbWZkbQ=,iv:7QCeKR8iCc1EQ2fSZW7P1jtSN2ikNSs1DrVB/BeOWHo=,tag:4iVQOmGhrpG44zgeGkL2KQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
