apiVersion: ENC[AES256_GCM,data:EVQ=,iv:UWNa3f+f4sMMHcv7qbpHPgMboeONga5oFTtB71Fu9qs=,tag:7eOtpXZTdjxbvLmUcNFCtQ==,type:str]
kind: ENC[AES256_GCM,data:y+4tGG4m,iv:hiqKaVncwx+IPzbVPgYXBHAl6UOZipAWA9GDEQB9hqM=,tag:Y2rafhwZ8pEoozzKD1OQew==,type:str]
metadata:
    name: ENC[AES256_GCM,data:wp3wdk7brm+WzREPQhxjuqIxhMLL,iv:mtbuGs3cRopxzCcgzpsGEMZouTV8Gjtzpl1lTryKEoo=,tag:iQp9w+kY7E7AcdUmadZIIg==,type:str]
    namespace: ENC[AES256_GCM,data:ao5JeqjfM3FiFBk=,iv:1b/ZSujfSgtcGkWIGerbhH6064lL5Xf4z+wx95uylKs=,tag:9BiHViUlDm8QivnaZBfXIQ==,type:str]
stringData:
    FILES_HOST: ENC[AES256_GCM,data:O63beuPxMz4n/mwYbH2XkA==,iv:1xzgBh3n+3YeLJfHWDB1xaF4kNVjAJSQpYYBruOf/b0=,tag:k/lUSb0/crTJCNE0kxie5Q==,type:str]
    PLEX_HOST: ENC[AES256_GCM,data:BeAbLP6O3VgcbJIvIsOn,iv:pox/3+UwhfdmJe47cGHTvHUdSfKEEM6ppPI7XiHm+FQ=,tag:Aolzz0CZbuH1zNWBfzNWdQ==,type:str]
    PLEX_VIA_HOST: ENC[AES256_GCM,data:cUkwG61mMAxktgXRSFF/,iv:+Sy6lHar6mqC7E48jQPmoxk15XIa6ffrOer0y8CjDSw=,tag:N+yEbY/k3UM9s9fV1X4xUg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQdjFVWnlsb0RxbE9NME80
            YkJWSjhKclcvYW1vOEJMcnJYNmFsSWhTaG5zCk16akhLamU2Y2VZTERjY2RmVnVu
            WlBublVnVVo5UUVHbWRyUHF1SGhVVWcKLS0tIFBxL1VCend4RVYrVUVpdDBvWExE
            UUlFc1RiQUdDRkgxdjBWUlFmOTNvYlEK2rhk1LNJ/QYg8de5x7WfI9VX26CAEWgH
            nekYeDQ1Bct8nsjlbv0NIvHOQyFtORAtzqT3nN04ZRjg4CA+yVTUCA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jxtdxm70ltr637yy5c00586r9q5mfx8ldgw8r5ye2cehpncygupsmjxjwh
    lastmodified: "2026-09-07T06:35:41Z"
    mac: ENC[AES256_GCM,data:yWQL5BZPGJmBVYiZAK30y33RYt1Yhcg8X9ywPV9MY4E5M6q0cDfcj296/DK1tvXFEXJiSDNr+xd8PQROKkmtEzF8h+r/ybB81bz4nuQOlJgG+EqQaQHITsqZKrvhYQ+P3FKguIn6RgkO2b6fy8wEKsmuwhWzi96oE6DTwIJuYRo=,iv:dc/egln4ngygCcOxrsaA3bLcVrR68ZUSz/3Ey2Y31vc=,tag:8DytlFL7adaIrxJz+u+F0A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
