apiVersion: ENC[AES256_GCM,data:rp0=,iv:DAFEn/yLi9fxGgXZN6H54NPDPzaizkgSeHHqcCddrUY=,tag:SEKED3X/LRqSbaasqGtDEg==,type:str]
data:
    server-addr: ENC[AES256_GCM,data:kfR/ynxY6n2E95Xiw3R/qjLmdjVV7C/L,iv:RDTbGEiAVFVlgmeGT4BaUSnLYXAbzz5ij3g25IYCtTU=,tag:mtRS1HQM1WbDLdXZjvqvjQ==,type:str]
    token: ENC[AES256_GCM,data:MVNg2K5KOGzWXBPFrmTytO50sFQx8n3mfAW9UISMDt37JepDj8pLMOqSu4izoHVUu7i+E6ntI17LwFo0,iv:MfA35OhxmOiRJcCdBqmmly/vPfX/cXy0ZFPDByIf3aI=,tag:/3QGzOKUIegsSRsSZjs2Bg==,type:str]
kind: ENC[AES256_GCM,data:j19d8KQN,iv:XOCfsPkvi3C64Q4EKbyVn2l0Lhd6Yisb5rKxT/A6xB0=,tag:NAQP6XHctwDX3rdtzWoAWQ==,type:str]
metadata:
    creationTimestamp: null
    name: ENC[AES256_GCM,data:itAZT4pe2CfH,iv:H/JpfAX202z72VAmKXYoON73oTEj3IQ9kUiXpdU25Lw=,tag:+dDKPdVwXBz71zGk52LM6A==,type:str]
    namespace: ENC[AES256_GCM,data:mo63Z8/yhs3Jog==,iv:EXqxjmUjB2mzytEH2vVYFwOc3LKjg5RiAid+oZWFS5M=,tag:yLxDteCzNsZ3asRq76kU0Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqQ2pWN2JxUTFGc21qQitm
            UVU0QUFLQllaNUJqdUVLdXg5MnZyZEgrNm0wCkN0MEdrOTltMEk2UG4rN0FqR0c4
            TUlKL0pQNDZUMDVKUlpHdy96MVZDR1kKLS0tIDYzbUk5STRic21ZMks4YW5XTjh0
            YnJhUGEvQTVvSVd5NUw4cW5Db1g1RWcKuT+YSBt6z3NXngPig+j8b2SrTF3HzvS4
            0VwIrJ6HZJQOC3dXCZ0yLyq3d+Uy/EjxSU1610uVigUDCMIKnUfHuQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jxtdxm70ltr637yy5c00586r9q5mfx8ldgw8r5ye2cehpncygupsmjxjwh
    lastmodified: "2026-05-29T19:40:34Z"
    mac: ENC[AES256_GCM,data:NyI4NFVp51l5SUFXOK2zxcyyEeaPbUSFy8DLVw5B64UjInaBOYR5CUIuE++9bNoVlV+g/cf4+lam1Z6qWB89/VzGO5t4FIPgzcAomrrabRYZUL0PBsjP17o9LGGPDyAUyLSkVQogSo0Kt+geV6DK0fYakrRYxUI2aLndj9DC160=,iv:S7YEqyV0GMujTS+8J7R977OuDnlO/hMgaCb+ImN2yLU=,tag:E7cCpB3wnp4aS6p9y7GjDA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
